name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env: #GLOBALES
  NODE_VERSION: "20"
  APP_NAME: cron-ticker-v2
  
jobs:
  # JOB 1 LINT
  lint:
    name: lint
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint

  # JOB 2 TEST
  test:
    name: Test
    runs-on: ububtu-latest
    needs: lint    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - name: Run test with coverage
      - run: npm run test:coverage 

  # JOB 3 BUILD
  build:
    name: Build
    runs-on: ububtu-latest
    needs: test 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build